###############################
# Author by : CyberAR    #
# Channel Youtube : CyberAR  #
# Create : Selasa, 6 Feb 2019 #
# selesai jam : 00:53 malam   #
###############################
z="
";hBz='${k}';VCz='"${p';WBz='b}║~';QCz='N${m';dCz='ana';LCz='k}BU';jz='clea';KBz='🕜═╗';Vz='T=`d';qBz='╚═══';DBz='"${b';QBz='M:"$';ABz='KALE';Hz='\033';hz='TAHU';xz='KTU ';cz='GAL=';aBz='${m}';SCz='{b}~';Oz='h="\';ZBz='IT:"';TBz='}$JA';iz='+%Y`';gz='+%m`';mz='ana(';BBz='NDER';tBz='   $';XCz='}║';NBz='╗"';fz='N=`d';HCz='AL${';XBz='║${k';NCz='"${m';dBz='ENIT';wz='S WA';FBz=' ╔══';vz='TOOL';cCz='(){';oz='echo';FCz='AL:"';Gz='pu="';uBz=' ${p';lBz='TIK$';ZCz='╝${b';Yz='DETI';sBz='╝"';bCz='main';OBz=' ║${';iBz='K:${';Tz='H`';Cz='33;1';yz='DAN ';Nz='34;1';EBz='}   ';kz='r';JBz='╔═══';lz='rusm';jBz='m}["';JCz='{b}║';az='+%S`';bBz='[${p';cBz='u}$M';pz=' -e ';mBz='{m}]';YCz='} ╚═';vBz='u}📆';MBz='═🕛═';TCz='}TAH';uz='{pu}';ACz='═══╗';oBz=' ╚══';aCz='}';bz='TANG';Lz='36;1';WCz='AHUN';dz='d`';yBz='} ╔═';LBz='${b}';Az='k="\';PBz='k}JA';Rz='`dat';pBz='══╝$';MCz='LAN:';VBz='}]${';OCz='}[${';SBz='${pu';Qz='JAM=';Iz='[39;';fBz='}║${';wBz='📆 $';nz='){';Kz='p="\';GCz='u}$T';Zz='K=`d';PCz='pu}$';Ez='m="\';eBz=']${b';Pz='32;1';ECz='ANGG';tz='}[ $';Uz='MENI';RBz='{m}[';rBz='═══╝';ICz='m}]$';HBz='══╗$';sz=' ${m';Xz='+%M`';GBz='════';Jz='1m"';CCz='} ║$';Bz='033[';DCz='{k}T';KCz='~║${';Fz='31;1';Sz='e +%';Dz='m"';nBz='║';rz='    ';UBz='M${m';YBz='}MEN';Mz='b="\';gBz='b}~║';BCz='╗${b';Wz='ate ';kBz='}$DE';RCz='b}║$';IBz='{b} ';xBz='"';CBz='}]"';ez='BULA';UCz='UN:$';qz='"   ';
eval "$Az$Bz$Cz$Dz$z$Ez$Bz$Fz$Dz$z$Gz$Hz$Iz$Jz$z$Kz$Bz$Lz$Dz$z$Mz$Bz$Nz$Dz$z$Oz$Bz$Pz$Dz$z$Qz$Rz$Sz$Tz$z$Uz$Vz$Wz$Xz$z$Yz$Zz$Wz$az$z$bz$cz$Rz$Sz$dz$z$ez$fz$Wz$gz$z$hz$fz$Wz$iz$z$jz$kz$z$lz$mz$nz$z$oz$z$oz$pz$qz$rz$sz$tz$uz$vz$wz$xz$yz$ABz$BBz$sz$CBz$z$oz$pz$DBz$EBz$FBz$GBz$HBz$IBz$JBz$GBz$KBz$LBz$FBz$GBz$MBz$NBz$z$oz$pz$DBz$EBz$OBz$PBz$QBz$RBz$SBz$TBz$UBz$VBz$WBz$LBz$XBz$YBz$ZBz$aBz$bBz$cBz$dBz$aBz$eBz$fBz$gBz$hBz$Yz$iBz$jBz$SBz$kBz$lBz$mBz$LBz$nBz$z$oz$pz$DBz$EBz$oBz$GBz$pBz$IBz$qBz$GBz$rBz$LBz$oBz$GBz$GBz$sBz$z$oz$pz$qz$rz$rz$tBz$RBz$uBz$vBz$ABz$BBz$wBz$mBz$xBz$z$oz$pz$DBz$yBz$GBz$GBz$ACz$LBz$FBz$GBz$GBz$BCz$yBz$GBz$GBz$ACz$xBz$z$oz$pz$DBz$CCz$DCz$ECz$FCz$aBz$bBz$GCz$ECz$HCz$ICz$JCz$LBz$KCz$LCz$MCz$NCz$OCz$PCz$ez$QCz$VBz$RCz$SCz$XBz$TCz$UCz$RBz$VCz$GCz$WCz$aBz$eBz$XCz$z$oz$pz$DBz$YCz$GBz$GBz$rBz$LBz$oBz$GBz$GBz$ZCz$YCz$GBz$GBz$rBz$xBz$z$oz$z$aCz$z$bCz$cCz$z$lz$dCz$z$aCz$z$bCz" 
